apiVersion: v1
kind: Service
metadata:
  name: pythonapi
spec:
  selector:
    app: pythonapi
  ports: 
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: v1
kind: Pod
metadata:
  name: pythonapi
  labels:
    app: pythonapi
spec:
  containers:
  - name: pythonapi
    image: cmayman/pythonapi:latest
    ports:
    - containerPort: 8080